"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def sumEvenFibonacci():
    result = 0
    num = 0
    first_num = 1
    second_num = 1

    while num < 4000000:
        num = first_num + second_num
        first_num, second_num = second_num, num

        if num % 2 == 0:
            result += num
    return result

def sumEvenFibonacci_1():
    result = 0
    first_num = 1
    second_num = 1
    num = first_num + second_num

    while num < 4000000:
        result += num
        first_num = second_num + num
        second_num = first_num + num
        num = first_num + second_num

    return result

if __name__ == "__main__":
    print("Result With 1st Function : " , sumEvenFibonacci())
    print("Result With 2nd Function : " , sumEvenFibonacci_1())
