"""
This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ''.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
"""

def spotTheDifference(s, t):
    wordDict = {}

    for char in s:
        if char not in wordDict:
            wordDict[char] = 0
        wordDict[char] += 1

    for char in t:
        if char not in wordDict:
            return char
        else:
            if wordDict[char] == 1:
                del wordDict[char]
            else:
                wordDict[char] -= 1

    return ''

print(spotTheDifference('foobar', 'barfoot'))
print(spotTheDifference('ide', 'idea'))
print(spotTheDifference('coding', 'ingcod'))